- hosts: bahmni-emr

  roles:
    - { role: httpd-maintenance, maintenance_status: start }

- hosts: bahmni-emr
  tasks:
   - name: Stop openmrs
     service: name=openmrs state=stopped
     when: db_name == 'openmrs' and (passive is not defined or passive != 'yes')
     become: yes

- hosts: bahmni-reports
  tasks:
   - name: Stop bahmni-reports
     service: name=bahmni-reports state=stopped
     when: db_name == 'openmrs' and (passive is not defined or passive != 'yes')
     become: yes

- hosts: bahmni-lab
  tasks:
   - name: Stop bahmni-lab
     service: name="bahmni-lab" state=stopped
     when: db_name == 'clinlims' and (passive is not defined or passive != 'yes')
     become: yes

- hosts: bahmni-erp
  tasks:
   - name: Stop bahmni-erp
     service: name=openerp state=stopped
     when: db_name == 'openerp' and (passive is not defined or passive != 'yes')
     become: yes

- hosts: bahmni-erp
  tasks:
   - name: Stop bahmni-erp-connect
     service: name=bahmni-erp-connect state=stopped
     when: db_name == 'openerp' and (passive is not defined or passive != 'yes')
     become: yes

- hosts: pacs-integration
  tasks:
   - name: Stop pacs-integration
     service: name=pacs-integration state=stopped
     when: db_name == 'bahmni_pacs' and (passive is not defined or passive != 'yes')
     become: yes

- hosts: dcm4chee
  tasks:
   - name: Stop dcm4chee
     service: name=dcm4chee state=stopped
     when: db_name == 'pacsdb' and (passive is not defined or passive != 'yes')
     become: yes



- hosts: bahmni-emr-db
  become: yes
  roles:
    - { role: mysql-db-restore, when: db_name == 'openmrs' }

- hosts: bahmni-lab-db
  become: yes
  roles:
    - { role: postgres-db-restore, when: db_name == 'clinlims' }

- hosts: bahmni-erp-db
  become: yes
  roles:
    - { role: postgres-db-restore, when: db_name == 'openerp' }

- hosts: pacs-integration-db
  become: yes
  roles:
    - { role: postgres-db-restore, when: db_name == 'bahmni_pacs' }

- hosts: dcm4chee-db
  become: yes
  roles:
    - { role: postgres-db-restore, when: db_name == 'pacsdb' }



- hosts: bahmni-emr
  tasks:
   - name: Start openmrs
     service: name=openmrs state=started
     when: db_name == 'openmrs' and (passive is not defined or passive != 'yes')
     become: yes

- hosts: bahmni-reports
  tasks:
   - name: Start bahmni-reports
     service: name=bahmni-reports state=started
     when: db_name == 'openmrs' and (passive is not defined or passive != 'yes')
     become: yes

- hosts: bahmni-lab
  tasks:
   - name: Start bahmni-lab
     service: name=bahmni-lab state=started
     when: db_name == 'clinlims' and (passive is not defined or passive != 'yes')
     become: yes

- hosts: bahmni-erp
  tasks:
   - name: Start openerp
     service: name=openerp state=started
     when: db_name == 'openerp' and (passive is not defined or passive != 'yes')
     become: yes

- hosts: bahmni-erp
  tasks:
   - name: Start bahmni-erp
     service: name=bahmni-erp-connect state=started
     when: db_name == 'openerp' and (passive is not defined or passive != 'yes')
     become: yes

- hosts: pacs-integration
  tasks:
   - name: Start pacs-integration
     service: name=pacs-integration state=started
     when: db_name == 'bahmni_pacs' and (passive is not defined or passive != 'yes')
     become: yes

- hosts: dcm4chee
  tasks:
   - name: Start dcm4chee
     service: name=dcm4chee state=started
     when: db_name == 'pacsdb' and (passive is not defined or passive != 'yes')
     become: yes

- hosts: bahmni-emr

  roles:
    - { role: httpd-maintenance, maintenance_status: end }