- hosts: all

  roles:
    - { role: selinux, selinux_state: enforcing, selinux_policy: targeted }
    - { role: bahmni-base }
    - { role: bahmni-user }
    - { role: installer-config }
    - { role: bahmni-support-user }
  tags:
    - setup

- hosts: bahmni-emr

  tasks:
   - include: roles/mysql-replication/tasks/stop_emr.yml
     when: passive is not defined or passive != 'yes'

- hosts: bahmni-emr-db

  roles:
    - { role: mysql-replication }
  tags:
    - repl

- hosts: bahmni-emr-db-slave

  roles:
    - { role: mysql-replication }
  tags:
    - repl

- hosts: bahmni-emr

  tasks:
   - include: roles/mysql-replication/tasks/start_emr.yml
     when: passive is not defined or passive != 'yes'
