- hosts: all

  roles:
    - { role: selinux, selinux_state: enforcing, selinux_policy: targeted }
    - { role: bahmni-base }
    - { role: bahmni-user }
    - { role: installer-config }
    - { role: bahmni-support-user }
  tags:
    - setup

- hosts: bahmni-erp

  tasks:
   - name: Stop openerp
     service:
       name: openerp
       state: stopped
     when: passive is not defined or passive != 'yes'

- hosts: bahmni-lab

  tasks:
   - name: Stop bahmni-lab
     service:
       name: bahmni-lab
       state: stopped
     when: passive is not defined or passive != 'yes'

- hosts: pacs-integration

  tasks:
   - name: Stop pacs-integration
     service:
       name: pacs-integration
       state: stopped
     when: passive is not defined or passive != 'yes'

- hosts: dcm4chee

  tasks:
   - name: Stop dcm4chee
     service:
       name: dcm4chee
       state: stopped
     when: passive is not defined or passive != 'yes'

- hosts: bahmni-erp-db:bahmni-erp-db-slave

  roles:
    - { role: postgres, postgres_user: openerp }
    - { role: postgres-replication, replication_user: openerp, master_db: "{{ groups['bahmni-erp-db'][0] }}" }

- hosts: bahmni-lab-db:bahmni-lab-db-slave

  roles:
    - { role: postgres, postgres_user: clinlims}
    - { role: postgres-replication, replication_user: clinlims, master_db: "{{ groups['bahmni-lab-db'][0] }}",
        when: "{{inventory_hostname not in groups['bahmni-erp-db-slave'] }}" }

- hosts: pacs-integration-db:pacs-integration-db-slave

  roles:
    - { role: postgres, postgres_user: pacs}
    - { role: postgres-replication, replication_user: pacs, master_db: "{{ groups['pacs-integration-db'][0] }}",
        when: "{{inventory_hostname not in groups['bahmni-erp-db-slave']
        and inventory_hostname not in groups['bahmni-lab-db-slave'] }}" }

- hosts: dcm4chee-db:dcm4chee-db-slave

  roles:
    - { role: postgres }
    - { role: postgres-replication, replication_user: postgres, master_db: "{{ groups['dcm4chee-db'][0] }}",
            when: "{{inventory_hostname not in groups['bahmni-erp-db-slave']
            and inventory_hostname not in groups['bahmni-lab-db-slave']
            and inventory_hostname not in groups['pacs-integration-db-slave']}}" }
  tags: dcm4chee

- hosts: bahmni-erp

  tasks:
   - name: Start openerp
     service:
       name: openerp
       state: started
     when: passive is not defined or passive != 'yes'

- hosts: bahmni-lab

  tasks:
   - name: Start bahmni-lab
     service:
       name: bahmni-lab
       state: started
     when: passive is not defined or passive != 'yes'

- hosts: pacs-integration

  tasks:
   - name: Start pacs-integration
     service:
       name: pacs-integration
       state: started
     when: passive is not defined or passive != 'yes'

- hosts: dcm4chee

  tasks:
   - name: Start dcm4chee
     service:
       name: dcm4chee
       state: started
     when: passive is not defined or passive != 'yes'

